//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planlayıcı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Users
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Username { get; set; }
        public Nullable<int> Password { get; set; }
        public string TC { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string Adrress { get; set; }
        public string Usertype { get; set; }
    }
}
