//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planlayıcı
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_program
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public Nullable<System.DateTime> Starttime { get; set; }
        public string Eventtype { get; set; }
        public string Explanation { get; set; }
        public Nullable<int> Userid { get; set; }
    }
}
